apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: media
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: truenas-jellyfin
  resources:
    requests:
      storage: 2Ti
