apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-jellyfin
  labels:
    app.kubernetes.io/part-of: homelab
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.151
    path: /mnt/HDD/hdd/jellyfin
    readOnly: true
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=3
