apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-music
  labels:
    app.kubernetes.io/part-of: homelab
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.151
    path: /mnt/SSD/ssd/Jellyfin
    readOnly: true
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=3
